"""Train the BERT sentiment model without relying on Trainer.

The repository cannot store the final 300MB+ weight file on GitHub. This
script keeps the model pipeline reproducible in three situations:

1. If `model/weights/best_model` already contains real weights, continue from it.
2. If the machine can reach HuggingFace, fine-tune `bert-base-chinese`.
3. If neither is true, initialize BERT from the local config and tokenizer, then
   train it on `data/processed/*.csv` to generate local weights.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Tuple

import pandas as pd
import torch
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from torch.optim import AdamW
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm
from transformers import BertConfig, BertForSequenceClassification, BertTokenizer


logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


BASE_MODEL_NAME = "bert-base-chinese"
LOCAL_MODEL_DIR = Path("model/weights/best_model")
PROCESSED_DATA_DIR = Path("data/processed")
REPORT_DIR = Path("reports")
WEIGHT_FILENAMES = ("model.safetensors", "pytorch_model.bin", "tf_model.h5")


class SentimentDataset(Dataset):
    """PyTorch dataset that tokenizes one review into BERT input tensors."""

    def __init__(self, texts, labels, tokenizer: BertTokenizer, max_len: int = 128):
        self.texts = list(texts)
        self.labels = list(labels)
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self) -> int:
        return len(self.texts)

    def __getitem__(self, idx: int):
        text = str(self.texts[idx])
        label = int(self.labels[idx])
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt",
        )
        return {
            "input_ids": encoding["input_ids"].flatten(),
            "attention_mask": encoding["attention_mask"].flatten(),
            "labels": torch.tensor(label, dtype=torch.long),
        }


def has_model_weights(model_dir: Path = LOCAL_MODEL_DIR) -> bool:
    """Return True only when the directory contains real model weights."""

    return model_dir.exists() and any((model_dir / name).exists() for name in WEIGHT_FILENAMES)


def load_tokenizer_and_model(num_labels: int = 2) -> Tuple[BertTokenizer, BertForSequenceClassification]:
    """Load a usable tokenizer/model pair with an offline-safe fallback."""

    if has_model_weights():
        logger.info("Loading local fine-tuned model from %s", LOCAL_MODEL_DIR)
        tokenizer = BertTokenizer.from_pretrained(LOCAL_MODEL_DIR)
        model = BertForSequenceClassification.from_pretrained(LOCAL_MODEL_DIR, num_labels=num_labels)
        return tokenizer, model

    try:
        logger.info("Local weights are missing; trying online base model: %s", BASE_MODEL_NAME)
        tokenizer = BertTokenizer.from_pretrained(BASE_MODEL_NAME)
        model = BertForSequenceClassification.from_pretrained(BASE_MODEL_NAME, num_labels=num_labels)
        return tokenizer, model
    except Exception as exc:
        logger.warning("Could not download %s: %s", BASE_MODEL_NAME, exc)
        logger.warning("Falling back to local config/tokenizer and random BERT initialization.")
        if not (LOCAL_MODEL_DIR / "config.json").exists():
            raise FileNotFoundError(
                "Missing model/weights/best_model/config.json. "
                "Download the shared weight package or keep config/tokenizer files in the repo."
            ) from exc
        tokenizer = BertTokenizer.from_pretrained(LOCAL_MODEL_DIR)
        config = BertConfig.from_pretrained(LOCAL_MODEL_DIR)
        config.num_labels = num_labels
        config.problem_type = "single_label_classification"
        model = BertForSequenceClassification(config)
        return tokenizer, model


def load_processed_data() -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Load train/validation/test CSV files generated by data_preprocess.py."""

    paths = {
        "train": PROCESSED_DATA_DIR / "train.csv",
        "val": PROCESSED_DATA_DIR / "val.csv",
        "test": PROCESSED_DATA_DIR / "test.csv",
    }
    missing = [str(path) for path in paths.values() if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "Processed dataset is missing: "
            + ", ".join(missing)
            + ". Run `python model/data_preprocess.py` first."
        )

    train_df = pd.read_csv(paths["train"])
    val_df = pd.read_csv(paths["val"])
    test_df = pd.read_csv(paths["test"])
    required_columns = {"clean_content", "label"}
    for name, df in (("train", train_df), ("val", val_df), ("test", test_df)):
        if not required_columns.issubset(df.columns):
            raise ValueError(f"{name}.csv must contain columns: {sorted(required_columns)}")
    return train_df, val_df, test_df


def evaluate(model, data_loader: DataLoader, device: torch.device) -> Tuple[float, list[int], list[int]]:
    """Run one evaluation pass and return accuracy, labels and predictions."""

    model.eval()
    predictions: list[int] = []
    labels_all: list[int] = []
    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)
            outputs = model(input_ids, attention_mask=attention_mask)
            preds = torch.argmax(outputs.logits, dim=1)
            predictions.extend(preds.cpu().numpy().tolist())
            labels_all.extend(labels.cpu().numpy().tolist())

    if not labels_all:
        return 0.0, labels_all, predictions
    return accuracy_score(labels_all, predictions), labels_all, predictions


def train() -> None:
    """Train and save the best sentiment model."""

    LOCAL_MODEL_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    Path("logs").mkdir(exist_ok=True)

    train_df, val_df, test_df = load_processed_data()
    logger.info("Dataset sizes: train=%s, val=%s, test=%s", len(train_df), len(val_df), len(test_df))
    if len(train_df) < 2:
        raise ValueError("Training data is too small. Check data/raw/comments.csv and preprocessing output.")

    tokenizer, model = load_tokenizer_and_model(num_labels=2)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    logger.info("Using device: %s", device)

    train_dataset = SentimentDataset(train_df["clean_content"].values, train_df["label"].values, tokenizer)
    val_dataset = SentimentDataset(val_df["clean_content"].values, val_df["label"].values, tokenizer)
    test_dataset = SentimentDataset(test_df["clean_content"].values, test_df["label"].values, tokenizer)

    batch_size = min(4, len(train_dataset))
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    optimizer = AdamW(model.parameters(), lr=2e-5)
    epochs = int(os.getenv("BERT_TRAIN_EPOCHS", "5"))
    best_val_acc = -1.0
    logger.info("Starting training for %s epochs", epochs)

    for epoch in range(epochs):
        model.train()
        total_loss = 0.0
        train_bar = tqdm(train_loader, desc=f"Epoch {epoch + 1}/{epochs}")
        for batch in train_bar:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            optimizer.zero_grad()
            outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            loss.backward()
            optimizer.step()

            total_loss += float(loss.item())
            train_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        avg_loss = total_loss / max(1, len(train_loader))
        val_acc, _, _ = evaluate(model, val_loader, device)
        logger.info("Epoch %s: loss=%.4f, val_acc=%.4f", epoch + 1, avg_loss, val_acc)

        if val_acc >= best_val_acc:
            best_val_acc = val_acc
            model.save_pretrained(LOCAL_MODEL_DIR)
            tokenizer.save_pretrained(LOCAL_MODEL_DIR)
            logger.info("Saved best model to %s (val_acc=%.4f)", LOCAL_MODEL_DIR, val_acc)

    if not has_model_weights():
        raise RuntimeError("Training finished but no model weight file was saved.")

    logger.info("Loading saved best model for final test evaluation")
    model = BertForSequenceClassification.from_pretrained(LOCAL_MODEL_DIR)
    model.to(device)
    test_acc, test_labels, test_preds = evaluate(model, test_loader, device)

    if len(test_labels) > 1:
        precision, recall, f1, _ = precision_recall_fscore_support(
            test_labels, test_preds, average="binary", zero_division=0
        )
        results = {
            "accuracy": round(float(test_acc), 4),
            "precision": round(float(precision), 4),
            "recall": round(float(recall), 4),
            "f1": round(float(f1), 4),
            "test_size": len(test_labels),
            "best_val_accuracy": round(float(best_val_acc), 4),
            "weight_file_present": has_model_weights(),
        }
        logger.info("Test results: %s", results)
        with (REPORT_DIR / "test_results.json").open("w", encoding="utf-8") as f:
            json.dump(results, f, ensure_ascii=False, indent=2)
    else:
        logger.info("Test predictions=%s, labels=%s", test_preds, test_labels)

    logger.info("Training completed")


if __name__ == "__main__":
    train()
